/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5b2e5381-a695-4961-88fb-3ac57f94dfda

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Check if Dist and Real.Angle are available.
-/
#check Dist
#check Real.Angle

/-
Formalization of Birkhoff's axioms for plane geometry.
Includes definitions for line measure and rays, and the BirkhoffPlane class with four postulates:
1. Line Measure: Lines are isometric to the reals.
2. Point-Line: Unique line through two points.
3. Angle Measure: Rays at a point are bijective to angles mod 2pi, and the angle between points is the difference of ray angles.
4. Similarity: SAS similarity implies full similarity (with equal angles).
-/
open Set Real

/-- A line measure is a bijection from R to the line that preserves distances. -/
def is_line_measure {P : Type*} (dist : P → P → ℝ) (l : Set P) (f : ℝ ≃ l) :=
  ∀ x y, dist (f x) (f y) = |x - y|

/-- A ray starting at O is the image of [0, ∞) under a line measure sending 0 to O. -/
def is_ray {P : Type*} (dist : P → P → ℝ) (Line : Set (Set P)) (r : Set P) (O : P) : Prop :=
  ∃ (l : Set P) (_ : l ∈ Line) (f : ℝ ≃ l),
    is_line_measure dist l f ∧
    f 0 = O ∧
    r = f '' {t | 0 ≤ t}



open Set Real

class BirkhoffPlane (P : Type*) where
  dist : P → P → ℝ
  Line : Set (Set P)
  angle : P → P → P → Real.Angle

  -- Postulate I: Line Measure
  line_measure : ∀ l ∈ Line, ∃ f : ℝ ≃ l, is_line_measure dist l f

  -- Postulate II: Point-Line
  unique_line : ∀ A B, A ≠ B → ∃! l ∈ Line, A ∈ l ∧ B ∈ l

  -- Postulate III: Angle Measure
  angle_measure : ∀ O : P, ∃ (meas : {r : Set P // is_ray dist Line r O} → Real.Angle),
    Function.Bijective meas ∧
    ∀ (A B : P), A ≠ O → B ≠ O →
      ∃ (rA rB : Set P) (hrA : is_ray dist Line rA O) (hrB : is_ray dist Line rB O),
        A ∈ rA ∧ B ∈ rB ∧
        angle A O B = (meas ⟨rB, hrB⟩ - meas ⟨rA, hrA⟩)

  -- Postulate IV: Similarity (Corrected)
  similarity : ∀ (A B C A' B' C' : P) (k : ℝ), k > 0 →
    dist A' B' = k * dist A B →
    dist A' C' = k * dist A C →
    angle B' A' C' = angle B A C →
    (dist B' C' = k * dist B C ∧ (angle C' B' A' =  angle C B A ∨ angle C' B' A' = - angle C B A ) ∧ angle A' C' B' = angle A C B)

/-
Theorem stating that the distance function is symmetric in the corrected Birkhoff Plane.
This follows from the Line Measure postulate, which relates distance to the absolute difference of real coordinates, and the symmetry of the absolute difference function.
-/
open Set Real

variable {P : Type*} [BirkhoffPlane P]

theorem BirkhoffPlane.dist_comm (A B : P) : BirkhoffPlane.dist A B = BirkhoffPlane.dist B A := by
  cases' ‹BirkhoffPlane P› with dist line angle h1 h2 h3 h4;
  by_cases h : A = B;
  · rw [ h ];
  · obtain ⟨ l, hl ⟩ := h2 A B h;
    obtain ⟨ f, hf ⟩ := h1 l hl.1.1;
    -- Since $A$ and $B$ are in $l$, there exist $x$ and $y$ such that $f(x) = A$ and $f(y) = B$.
    obtain ⟨x, hx⟩ : ∃ x : ℝ, f x = A := by
      exact ⟨ f.symm ⟨ A, hl.1.2.1 ⟩, by simp +decide ⟩
    obtain ⟨y, hy⟩ : ∃ y : ℝ, f y = B := by
      exact ⟨ f.symm ⟨ B, hl.1.2.2 ⟩, by simp +decide ⟩;
    have := hf x y; have := hf y x; simp_all +decide [ abs_sub_comm ] ;

/-
Theorem stating that the distance between two points is zero if and only if the points are identical in the corrected Birkhoff Plane.
This follows from the Line Measure postulate. If A = B, distance is 0. If distance is 0, then |xA - xB| = 0, so xA = xB, and since the map is a bijection, A = B.
-/
open Set Real

variable {P : Type*} [BirkhoffPlane P]

theorem BirkhoffPlane.dist_eq_zero_iff (A B : P) : BirkhoffPlane.dist A B = 0 ↔ A = B := by
  cases' ‹BirkhoffPlane P› with dist line measure line_measure unique_line angle_measure similarity;
  by_cases h : A = B <;> simp +decide [ h ];
  · by_contra h_nonzero;
    obtain ⟨ f, hf ⟩ := line_measure _ ( Classical.choose_spec ( show ∃ l ∈ line, B ∈ l from by
                                                                  obtain ⟨ l, hl ⟩ := angle_measure B;
                                                                  obtain ⟨ r, hr ⟩ := hl.1.2 0;
                                                                  rcases r with ⟨ r, hr ⟩;
                                                                  rcases ‹is_ray dist line r B› with ⟨ l, hl, f, hf, rfl, rfl, rfl ⟩;
                                                                  exact ⟨ _, ‹_›, f 0 |>.2 ⟩ ) |>.1 );
    all_goals generalize_proofs at *;
    exact h_nonzero ( by simpa using hf ( f.symm ⟨ B, Classical.choose_spec ‹∃ x ∈ line, B ∈ x› |>.2 ⟩ ) ( f.symm ⟨ B, Classical.choose_spec ‹∃ x ∈ line, B ∈ x› |>.2 ⟩ ) );
  · obtain ⟨ l, hl₁, hl₂ ⟩ := unique_line A B h;
    obtain ⟨ f, hf ⟩ := line_measure l hl₁.1;
    obtain ⟨ x, hx ⟩ := f.surjective ⟨ A, hl₁.2.1 ⟩ ; obtain ⟨ y, hy ⟩ := f.surjective ⟨ B, hl₁.2.2 ⟩ ; simp_all +decide [ is_line_measure ];
    have := hf x y; simp_all +decide [ sub_eq_zero ] ;
    grind




/-
Definitions for betweenness and midpoint in the corrected Birkhoff Plane.
These are necessary prerequisites for proving the existence of a midpoint.
-/
open Set Real

variable {P : Type*} [BirkhoffPlane P]

/-- B is between A and C if d(A, C) = d(A, B) + d(B, C). -/
def BirkhoffPlane.between (A B C : P) : Prop :=
  BirkhoffPlane.dist A C = BirkhoffPlane.dist A B + BirkhoffPlane.dist B C


/-- The segment AB is the set of points X such that X is between A and B. -/
def BirkhoffPlane.segment (A B : P) : Set P :=
  {X | BirkhoffPlane.between A X B}

/-- A triangle is defined by three points. -/
structure BirkhoffPlane.Triangle (P : Type*) where
  A : P
  B : P
  C : P

/-- Two triangles are congruent if there is a similarity with k=1. -/
def BirkhoffPlane.congruent (t1 t2 : BirkhoffPlane.Triangle P) : Prop :=
  BirkhoffPlane.dist t2.A t2.B = BirkhoffPlane.dist t1.A t1.B ∧
  BirkhoffPlane.dist t2.A t2.C = BirkhoffPlane.dist t1.A t1.C ∧
  BirkhoffPlane.dist t2.B t2.C = BirkhoffPlane.dist t1.B t1.C ∧
  BirkhoffPlane.angle t2.B t2.A t2.C = BirkhoffPlane.angle t1.B t1.A t1.C ∧
  BirkhoffPlane.angle t2.C t2.B t2.A = BirkhoffPlane.angle t1.C t1.B t1.A ∧
  BirkhoffPlane.angle t2.A t2.C t2.B = BirkhoffPlane.angle t1.A t1.C t1.B

theorem BirkhoffPlane.congruent_refl (t : BirkhoffPlane.Triangle P) : BirkhoffPlane.congruent t t := by
  simp [BirkhoffPlane.congruent]


/-- M is a midpoint of AB if M is between A and B and AM = MB. -/
def BirkhoffPlane.is_midpoint (A B M : P) : Prop :=
  BirkhoffPlane.between A M B ∧ BirkhoffPlane.dist A M = BirkhoffPlane.dist M B


/-
Lemma stating that for any two real numbers x and y, there exists a unique real number m such that the distance from x to m equals the distance from m to y, and m is between x and y (triangle equality holds). This m is simply (x + y) / 2.
-/
theorem Real.exists_unique_midpoint (x y : ℝ) : ∃! m, |x - m| = |m - y| ∧ |x - m| + |m - y| = |x - y| := by
  refine' ⟨ ( x + y ) / 2, _, _ ⟩ <;> norm_num;
  · exact ⟨ by cases abs_cases ( x - ( x + y ) / 2 ) <;> cases abs_cases ( ( x + y ) / 2 - y ) <;> cases abs_cases ( x - y ) <;> linarith, by cases abs_cases ( x - ( x + y ) / 2 ) <;> cases abs_cases ( ( x + y ) / 2 - y ) <;> cases abs_cases ( x - y ) <;> linarith ⟩;
  · intro z h1 h2; cases abs_cases ( x - z ) <;> cases abs_cases ( z - y ) <;> cases abs_cases ( x - y ) <;> linarith;



/-
Theorem stating that for any two points A and B, there exists a midpoint M in the corrected Birkhoff Plane.
This follows from the Line Measure postulate. If A = B, M = A. If A ≠ B, map the line AB to R, find the midpoint in R, and map it back.
-/
open Set Real

variable {P : Type*} [BirkhoffPlane P]

theorem BirkhoffPlane.exists_midpoint (A B : P) : ∃ M, BirkhoffPlane.is_midpoint A B M := by
  by_cases h : A = B <;> simp_all +decide [ BirkhoffPlane.is_midpoint ];
  · use B;
    field_simp;
    exact ⟨ by simp +decide [ BirkhoffPlane.between, BirkhoffPlane.dist_eq_zero_iff ], trivial ⟩;
  · have := ‹BirkhoffPlane P›.line_measure ( Classical.choose ( ‹BirkhoffPlane P›.unique_line A B h ) ) ( Classical.choose_spec ( ‹BirkhoffPlane P›.unique_line A B h ) |>.1.1 );
    obtain ⟨ f, hf ⟩ := this;
    -- Let $x$ and $y$ be the coordinates of $A$ and $B$ on the line $l$.
    obtain ⟨x, hx⟩ : ∃ x : ℝ, f x = ⟨A, Classical.choose_spec ( ‹BirkhoffPlane P›.unique_line A B h ) |>.1.2.1⟩ := by
      exact f.surjective _
    obtain ⟨y, hy⟩ : ∃ y : ℝ, f y = ⟨B, Classical.choose_spec ( ‹BirkhoffPlane P›.unique_line A B h ) |>.1.2.2⟩ := by
      exact f.surjective _;
    -- Let $m$ be the midpoint of $x$ and $y$.
    obtain ⟨m, hm⟩ : ∃ m : ℝ, |x - m| = |m - y| ∧ |x - m| + |m - y| = |x - y| := by
      exact ⟨ ( x + y ) / 2, by cases abs_cases ( x - ( x + y ) / 2 ) <;> cases abs_cases ( ( x + y ) / 2 - y ) <;> cases abs_cases ( x - y ) <;> linarith, by cases abs_cases ( x - ( x + y ) / 2 ) <;> cases abs_cases ( ( x + y ) / 2 - y ) <;> cases abs_cases ( x - y ) <;> linarith ⟩;
    refine' ⟨ f m |>.1, _, _ ⟩ <;> simp_all +decide [ BirkhoffPlane.between ];
    · have := hf x m; have := hf m y; have := hf x y; aesop;
    · have := hf x m; have := hf m y; aesop;

/-
Definition of collinearity and theorem stating that any two points are collinear in the corrected Birkhoff Plane.
This follows from the Unique Line postulate. If A ≠ B, there is a unique line containing them. If A = B, any line through A works (and one exists by Angle Measure or just logic).
-/
open Set Real

variable {P : Type*} [BirkhoffPlane P]

/-- A set of points is collinear if there exists a line containing them. -/
def BirkhoffPlane.collinear (s : Set P) : Prop :=
  ∃ l ∈ BirkhoffPlane.Line (P := P), s ⊆ l

theorem BirkhoffPlane.collinear_pair (A B : P) : BirkhoffPlane.collinear {A, B} := by
  by_cases h : A = B;
  · cases' ‹BirkhoffPlane P› with dist Line angle line_measure unique_line angle_measure similarity;
    rcases angle_measure A with ⟨ meas, hmeas₁, hmeas₂ ⟩;
    obtain ⟨ r, hr ⟩ := hmeas₁.2 0;
    obtain ⟨ l, hl₁, hl₂ ⟩ := r.2;
    use l;
    grind;
  · cases' ‹BirkhoffPlane P›.unique_line A B h with l hl B h;
    exact ⟨ l, hl.1.1, Set.insert_subset_iff.2 ⟨ hl.1.2.1, Set.singleton_subset_iff.2 hl.1.2.2 ⟩ ⟩


/-- Two lines are parallel if they are equal or disjoint. -/
def BirkhoffPlane.parallel (l1 l2 : Set P) : Prop :=
  l1 ∈ BirkhoffPlane.Line (P := P) ∧ l2 ∈ BirkhoffPlane.Line (P := P) ∧ (l1 = l2 ∨ l1 ∩ l2 = ∅)



/-
Theorem: If three points are collinear in the corrected Birkhoff Plane, they satisfy the triangle inequality.
Proof: They lie on a line `l` with a coordinate map `f`. The distances correspond to `|x_A - x_C|`, etc. The result follows from the triangle inequality for real numbers `|x - z| <= |x - y| + |y - z|`.
-/
open Set Real

variable {P : Type*} [BirkhoffPlane P]

theorem BirkhoffPlane.collinear_triangle_inequality (A B C : P) (h : BirkhoffPlane.collinear {A, B, C}) :
  BirkhoffPlane.dist A C ≤ BirkhoffPlane.dist A B + BirkhoffPlane.dist B C := by
  obtain ⟨ l, hl ⟩ := h;
  rcases ‹BirkhoffPlane P›.line_measure l hl.1 with ⟨ f, hf ⟩;
  -- Since $A$, $B$, and $C$ are on the line $l$, we can write $A = f(a)$, $B = f(b)$, and $C = f(c)$ for some $a, b, c \in \mathbb{R}$.
  obtain ⟨a, ha⟩ : ∃ a : ℝ, A = f a := by
    exact ⟨ f.symm ⟨ A, hl.2 ( by simp +decide ) ⟩, by simp +decide ⟩
  obtain ⟨b, hb⟩ : ∃ b : ℝ, B = f b := by
    exact ⟨ f.symm ⟨ B, hl.2 ( by simp +decide ) ⟩, by simp +decide ⟩
  obtain ⟨c, hc⟩ : ∃ c : ℝ, C = f c := by
    exact ⟨ f.symm ⟨ C, hl.2 ( by simp +decide ) ⟩, by simp +decide ⟩;
  simp +decide only [ha, hc, hb];
  rw [ hf a c, hf a b, hf b c ];
  exact abs_sub_le _ _ _

/-
Check if Real.Angle.cos exists.
-/
#check Real.Angle.cos
