/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1623e880-330d-45c9-a59c-5d5bf6030013

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have formalized Birkhoff's Postulate 3 (The Ruler Postulate).

The postulate states that the points of any line can be put into a 1:1 correspondence with the real numbers such that the distance between any two points corresponds to the absolute difference of their coordinates.

The formalization is provided in the definition `postulate_3`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped Real

/--
  The undefined elements of the geometry system are points and lines. The undefined relations are distance between points and angle between three points.
-/
structure ElementsUnconditional  where

  -- Points and Lines are undefined types
  Points : Type
  Lines : Type

  -- distance between two points and angle between three points are undefined functions
  dist : Points → Points → ℝ

  -- angle between three points A, O, B is the angle AOB with vertex at O. We need A ≠ O and B ≠ O to define the angle properly. By convention, if either A = O or B = O, then the angle AOB is defined to be 0.
  angle : Points → Points → Points → Real.Angle

/--
  Relations between points and lines: any two points determine a line, and a line determines the set of points lying on it.
-/
structure ElementsUnconditional_with_pt_line_relations extends ElementsUnconditional where

  -- "Any two distinct points determine a unique line" This is postulate II of Birkhoff's axioms; but we include it here as part of the basic definitions to facilitate further development. There are many lines passing through two indentical points, we can choose any one of them in this case. Usually, we will consider the 'horizontal' line passing through two identical points.
  mk_line_pt_pt : Points → Points → Lines

  -- A line determines the set of points lying on it
  get_pts_of_line : Lines → Set Points

  -- For any two points A and B, both A and B lie on the line determined by A and B. "points that make the line, lie on the line"
  mem_pts_line : ∀ A B : Points,
              A ∈ get_pts_of_line (mk_line_pt_pt A B) ∧
              B ∈ get_pts_of_line (mk_line_pt_pt A B)

  -- Any two distinct points lying on a line determine that line. "lines are determined by the points that lie on them"
  eq_line_of_pts : ∀ l : Lines,
              ∀ A B : Points,
              A ≠ B →
              A ∈ get_pts_of_line l →
              B ∈ get_pts_of_line l →
              l = mk_line_pt_pt A B

structure Elements extends ElementsUnconditional_with_pt_line_relations where

  -- Distance is non-negative
  dist_nonneg : ∀ A B : Points, 0 ≤ dist A B

  -- Distance is symmetric
  dist_symm : ∀ A B : Points, dist A B = dist B A

variable (e : Elements)

/--
  Coercion of line into the set of points lying on it.
-/
instance : Coe (e.Lines) (Set e.Points) :=
  ⟨fun l => e.get_pts_of_line l⟩

/-
Postulate III: The points of any line can be put into 1:1 correspondence with the real numbers x so that |x_A - x_B| = d(A, B) for all points A, B.
-/
/--
  Postulate III: The points of any line can be put into 1:1 correspondence with the real numbers x so that |x_A - x_B| = d(A, B) for all points A, B.
-/
def postulate_3 (e : Elements) : Prop :=
  ∀ l : e.Lines,
    ∃ f : e.Points → ℝ,
      Set.BijOn f (e.get_pts_of_line l) Set.univ ∧
      ∀ A B, A ∈ e.get_pts_of_line l → B ∈ e.get_pts_of_line l → |f A - f B| = e.dist A B